name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@main

      - name: Create .env file
        run: |  
        echo 'PORT=${{ secrets.PORT }} NGINXGROUP=${{ secrets.NGINXGROUP }} NGINXUSER=${{ secrets.NGINXUSER }} PHPGROUP=${{ secrets.PHPGROUP }} PHPUSER=${{ secrets.PHPUSER }}' > .env

      - name: Run Build
        run: docker-compose up -d