name: Laravel Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: apt update
        run: apt-get update -y && apt-get install -y libmcrypt-dev openssl
      - name: PDO install
        run: docker-php-ext-install pdo mcrypt mbstring
      - name: php install
        run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - name: PDO second install
        run: docker-php-ext-install pdo mcrypt mbstring

      - name: Copy app
        run: cp ./src /var/www/html

      - name: Create .env file
        run: echo 'PORT=${{ secrets.PORT }}' > .env
          # echo  > .env
          # echo 'NGINXUSER=${{ secrets.NGINXUSER }}' > .env
          # echo 'PHPGROUP=${{ secrets.PHPGROUP }}' > .env
          # echo 'PHPUSER=${{ secrets.PHPUSER }}' > .env

      - name: cd into /src && add APP_KEY
        run: cd ./src && cp .env.example .env && composer install

      - name: Run build
        run: docker-compose up -d

      # - name: Run Composer
      #   run: docker-compose run --rm composer install