name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@main

      - name: Create .env file
        run: echo 'PORT=${{ secrets.PORT }}' > .env

        run: echo 'NGINXGROUP=${{ secrets.NGINXGROUP }}' > .env
        run: echo 'NGINXUSER=${{ secrets.NGINXUSER }}' > .env
        run: echo 'PHPGROUP=${{ secrets.PHPGROUP }}' > .env
        run: echo 'PHPUSER=${{ secrets.PHPUSER }}' > .env

      - name: Run Build
        run: docker-compose up -d