name: Laravel Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@main

      - name: Create .env file
        run: echo 'PORT=${{ secrets.PORT }}' > .env
          # echo  > .env
          # echo 'NGINXUSER=${{ secrets.NGINXUSER }}' > .env
          # echo 'PHPGROUP=${{ secrets.PHPGROUP }}' > .env
          # echo 'PHPUSER=${{ secrets.PHPUSER }}' > .env

      - name: cd into /src && add APP_KEY
        run: cd ./src && cp .env.example .env && composer install && docker-compose run --rm artisan key:generate

      - name: Run build
        run: docker-compose up -d

      # - name: Run Composer
      #   run: docker-compose run --rm composer install