name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@main
      - name: Create .env file
        run: echo 'PORT=${{ secrets.PORT }}' > .env

      - name: Run Build
        run: docker-compose up -d